---
title: "MITx Analytics Edge: Unit 4: Trees: D2Hawkeye"
output: html_notebook
---



```{r}
Claims = read.csv("datasets/ClaimsData.csv")
str(Claims)
```

```{r}
table(Claims$bucket2009)/nrow(Claims)
```

```{r}
library(caTools)
set.seed(88)
spl = sample.split(Claims, SplitRatio=0.6)
ClaimsTrain = subset(Claims, spl == TRUE)
ClaimsTest = subset(Claims, spl == FALSE)
print(nrow(ClaimsTest))
print(nrow(ClaimsTrain))
```
```{r}
print(mean(ClaimsTrain$age))
print(sum(ClaimsTrain$diabetes > 0)/nrow(ClaimsTrain))
```
```{r}
tbl = table(ClaimsTest$bucket2009, ClaimsTest$bucket2008)
tbl
```
```{r}
sum(diag(tbl)) / nrow(ClaimsTest)
```
```{r}
PenaltyMatrix = matrix(c(0,1,2,3,4,2,0,1,2,3,4,2,0,1,2,6,4,2,0,1,8,6,4,2,0), byrow=TRUE, nrow=5)
penalized = as.matrix(tbl) * PenaltyMatrix
penalized
```
```{r}
sum(penalized)/nrow(ClaimsTest)
```

```{r}
library(rpart)
library(rpart.plot)

ClaimsTree = rpart(bucket2009 ~ age + arthritis + alzheimers + cancer + copd + depression + diabetes, data=ClaimsTrain, method="class", cp=0.00005)
prp(ClaimsTree)
```
```{r}
ClaimsTest = predict(ClaimsTree, newdata=ClaimsTest, type="class")
table(ClaimsTest$bucket2009, PredictTest)
```
```{r}

ClaimsTree = rpart(bucket2009 ~ age + arthritis + alzheimers + cancer + copd + depression + diabetes, data=ClaimsTrain, method="class", cp=0.00005, parms=list(loss=PenaltyMatrix))
ClaimsTest = predict(ClaimsTree, newdata=ClaimsTest, type="class")
table(ClaimsTest$bucket2009, PredictTest)
```

